server:
  port: 8090 #端口
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-dept-client #注册进服务中心的名字
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    url: jdbc:mysql://127.0.0.1:3360/springcloud #数据库url
    username: root #账密
    password: root
  jpa:
    show-sql: true #是否显示sql
    hibernate:
      ddl-auto: update #根据pojo自动创建表
  cache:
    ehcache:
      config: classpath:ehcache.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8092/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}} #注册中心显示的该服务的名称
    prefer-ip-address: true #显示ip地址
