spring:
  profiles:
    active: dev
---
server:
  port: 8090
spring:
  profiles: dev
  application:
    name: emp-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    ehcache:
      config: classpath:ehcache.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8092/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
